### ISSUE TITLE
Improve Kyber transaction handling to reduce risk of reverts.

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#314]
Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x7e065e5658b1f37b63379c0eef993fd9827c4960362e7a62802cec7eab779550",
  "blockNumber": 9417560,
  "contractAddress": null,
  "cumulativeGasUsed": 2245606,
  "from": "0x904d67de70f1ba8ec6f9a575fbd4bf2c568d7a11",
  "gasUsed": 382000,
  "logs": [],
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0xe1fc56b0ce9dbefeaae27293c4551200db41da15",
  "transactionHash": "0x25345f928d87cfec0a0e0fd6b55dd011e5dfc0ecf44d1c542270a4fd25a090ce",
  "transactionIndex": 20
}
    at t._next (https://interface.avantgarde-finance.now.sh/static/js/6.baab5fa0.chunk.js:2:930261)
    at t.__tryOrUnsub (https://interface.avantgarde-finance.now.sh/static/js/6.baab5fa0.chunk.js:2:65209)
    at t.next (https://interface.avantgarde-finance.now.sh/static/js/6.baab5fa0.chunk.js:2:64354)
    at t._next (https://interface.avantgarde-finance.now.sh/static/js/6.baab5fa0.chunk.js:2:63430)
    at t.next (https://interface.avantgarde-finance.now.sh/static/js/6.baab5fa0.chunk.js:2:63101)
    at e.value (https://interface.avantgarde-finance.now.sh/static/js/6.baab5fa0.chunk.js:2:921055)
    at https://interface.avantgarde-finance.now.sh/static/js/6.baab5fa0.chunk.js:2:920570
    at c (https://interface.avantgarde-finance.now.sh/static/js/6.baab5fa0.chunk.js:2:1578800)
    at Generator._invoke (https://interface.avantgarde-finance.now.sh/static/js/6.baab5fa0.chunk.js:2:1578553)
    at Generator.forEach.e.<computed> [as next] (https://interface.avantgarde-finance.now.sh/static/js/6.baab5fa0.chunk.js:2:1579157)
    at n (https://interface.avantgarde-finance.now.sh/static/js/6.baab5fa0.chunk.js:2:958186)
    at o (https://interface.avantgarde-finance.now.sh/static/js/6.baab5fa0.chunk.js:2:958397)

**Comment by fubhy** [comment]
As discussed this seems to be a problem with Kyber reserves updating their rates before submitting the transaction. I was thinking that in order to make it less likely to happen we could:

1. For all transactions, before sending the transaction (click on submit in transaction modal), we run another `estimateGas` call. If this fails, we know that the transaction would also fail,hence we reject it and tell the user that the state is no longer valid and that they have to re-start the transaction (get a new rate)
2. We re-fetch the rates every few seconds even when the user doesn't change the form values in the liquidity pool trading interfaces. Also, when the user clicks the button, we quickly re-fetch the rates too before submitting it to the modal.

That way, the likelihood of these failing transactions will be reduced. But we obviously can't prevent this entirely (there are other fail cases on kyber that we have no control over, e.g. block limit exhausted (trade volume for block higher than max. trade volume allowed per block on the reserve), imbalance, etc.).
